linters:
  enable:
    - gofmt
    - misspell
    - godot
    - whitespace
    - gci
    - errorlint
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/canonical/lxd-imagebuilder)
