name: Tests
on:
  - push
  - pull_request

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-tests:
    name: Code tests
    strategy:
      fail-fast: false
      matrix:
        go:
          - 1.21.x
          - 1.22.x
        os:
          - ubuntu-20.04
          - ubuntu-22.04
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Dependency Review
      #   uses: actions/dependency-review-action@v3
      #   if: github.event_name == 'pull_request'

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Install dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y --no-install-recommends squashfs-tools xdelta3

      - name: Update Go modules
        run: make update-gomod

      - name: Run static analysis
        run: make static-analysis

      - name: Unit tests (all)
        run: make check
